name: 'Run rector tests'

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'run rector tests'
                        run: vendor/bin/phpunit utils/rector/tests

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress --ansi
            -   run: ${{ matrix.actions.run }}
